"""Fix paid_on to DateTime

Revision ID: 1c743dbea258
Revises: 
Create Date: 2025-06-28 00:41:46.971006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c743dbea258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_payment')
    op.drop_table('billpayment')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.alter_column('bill_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('paid_on',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_column('due_date')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('admin', 'customer'), server_default=sa.text("'customer'"), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', mysql.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('paid_on',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('bill_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('billpayment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bill_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('paid_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bill_payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('biller', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
