"""add payer/payee email to transaction

Revision ID: 286dbd3e8c4b
Revises: 1c743dbea258
Create Date: 2025-12-01 23:38:47.049063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '286dbd3e8c4b'
down_revision = '1c743dbea258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payee_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('payer_email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('payer_email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('payee_email')

    # ### end Alembic commands ###
